### ISSUE TITLE
[ETAP 1][Poprawki] Wielkość ikonek przy dostawcach

### ISSUE THREAD

**Issue by uHappyLogic** [mjazdzewski1/projektBE#12]
![capture](https://user-images.githubusercontent.com/6952226/48315834-8b273080-e5db-11e8-9e7b-050793165075.PNG)

**Comment by uHappyLogic** [comment]
Chyba, że mają być takie duże. Jeśli tak to do zamknięcia.

**Comment by msobiecki** [comment]
Podpinam pod #5 robiąc poprawki do rozjezdzających elementów wyelminuje ten problem.
